### ISSUE TITLE
Command to turn on (and off) linum-relative

### ISSUE THREAD

**Issue by joonro** [coldnew/linum-relative#15]
Hi,

I'm using Evil mode and I want to turn on linum-relative when I'm in the normal state, and turn it off wen I'm in the insert state. I'm using `linum-relative-toggle` as a hook, but it does not work precisely. Could you please provide `linum-relative-on` and `linum-relative-off`so I can turn it on/off without ambiguity? 

Thank you so much!

**Comment by coldnew** [comment]
is commit b4162ba what yout want ?

**Comment by joonro** [comment]
Thank you so much for the quick reply. It is, but I think `linum-relative-on` should check if `(eq linum-format 'linum-relative)` first - a user can do `linum-relative-on` while `linum-format` is `linum-relative` and that will `(setq linum-format 'linum-relative)`.

**Comment by coldnew** [comment]
Fixes in f205dba
Thanks :)
