### ISSUE TITLE
linum-relative: Invalid function: with-helm-buffer

### ISSUE THREAD

**Issue by jgkamat** [coldnew/linum-relative#21]
I updated linum-relative today, and whenever I open a new helm window, I get this. 

`linum-relative: Invalid function: with-helm-buffer`

I don't want linum-relative in my helm buffers anyway, is there a way to turn this feature off?

I'm prety new to emacs, could someone tell me how to provide more debug info (if you need it)
I'm using the latest helm on melpa
Helm also updated today (so that might be the issue?)

**Comment by peterhadlaw** [comment]
+1

**Comment by coldnew** [comment]
@jgkamat Thanks for report this issue, I'll handle it. The helm feature just merge yesterday, I'll add config to enable/disable it .

**Comment by jgkamat** [comment]
Thanks! :smile:

**Comment by coldnew** [comment]
Use `(setq linum-relative-with-helm t)` to enable integrate with helm-mode, this feature is set to nil by default.

**Comment by jgkamat** [comment]
Thanks for the quick fix! Its looking good from my end now.

**Comment by izzycecil** [comment]
I'm not yet sure why, but I still am getting `byte-code: Invalid function: with-helm-buffer` whenever I attempt to open a helm window (such as trying to open file with `C-x C-f`), even with #27 . This happens regardless of whether or not `linum-relative-on` has ever been evoked. Helm works just fine without linum-relative. The `with-helm-buffer` seems to work just fine in other packages. Here is my linum-relative related configuration:
```elisp
  ;; Relative linum mode
   (use-package linum-relative
   :ensure t
   :init
    (setq linum-relative-current-symbol ""
             linum-relative-format "%3s"
             linum-relative-plusp-offset 1))
```
Any thoughts? Am I missing something? I'm going to continue looking into it.

**Comment by peterhadlaw** [comment]
I fixed this issue a while ago and then it resurfaced with recent updates.
I.e. I'm confirming I too am having this issue

**Comment by coldnew** [comment]
I try to use `emacs -q` to load the `linum-relative.el` and eval it. There's no such issue.
I'll re-test it with a minimal emacs config which has both `linum-relative` and `helm` later.

**Comment by thblt** [comment]
I have the same issue, but triggering it requires that linum-relative has been enabled at least once (not necessarily to be still actually activated anywhere).

**Comment by wujiang** [comment]
@coldnew, any updates? thanks.

**Comment by coldnew** [comment]
Can anyone give me a public emacs config or test in clean install with this issue ?

I use [this](https://github.com/coldnew/linum-relative-test-issue-21) as a minimal config to test this issue,
there's no `Invalid function: with-helm-buffer` problem when I use `M-x helm-find-files`.

I also test on `spacemacs` with clean install, no this issue yet.

**Comment by thblt** [comment]
I've been able to trigger the bug with this config:

~~~elisp
(require 'package)
(setq package-archives '(("melpa"     . "https://melpa.org/packages/"))) 
(package-initialize)
(package-install 'helm)
(package-install 'linum-relative)
~~~

This may not be as minimal/clean/elegant as one could hope, but I'm pretty new to Emacs, as you may already have noticed :-)

M-x `linum-relative-global-mode` M-x `helm-M-x` splits the window, then prints the message "linum-relative: Invalid function: with-helm-buffer".

**Comment by coldnew** [comment]
@thblt I can reproduce this issue, let me think how to handle this

**Comment by coldnew** [comment]
Workround: remove your `linum-relative.elc` and restart emacs and the error message is gone.

I think there's some problem when byte-compile the `linum-relative.el`, if anyone has this issue you can try the workround first.

I'm still finding the elegant way to solve this issue.

**Comment by coldnew** [comment]
I think this is fixed in commit 3bed92a . If anyone still has this error, please reopen the issue.

**Comment by thblt** [comment]
Thanks!

**Comment by dinojr** [comment]
The problem occurs again. Deleting linume-relative.elc fixes it.
