### ISSUE TITLE
Show current line number instead of "0"

### ISSUE THREAD

**Issue by ZzAntares** [coldnew/linum-relative#25]
Hi, I want to know if is there some setting I could apply in order to show the current line number instead of just seeing a zero on the linum, for example:

```
3
2
1
4  This is the current line|
1
2
3
```

Thanks in advance!

**Comment by coldnew** [comment]
I really need to find time to update the readme :)

You can set linum-relative-current-symbol variable to empty string, this will make linum-relative show real line number. ex:

(setq linum-relative-current-symbol "")

**Comment by ZzAntares** [comment]
Thanks!
