### ISSUE TITLE
How to use linum-format with linum-relative?

### ISSUE THREAD

**Issue by krzysztof-magosa** [coldnew/linum-relative#30]
Hi,
I would like to use linum-relative, but there is one issue with it.
When I set linum-format linum-relative stops working.
Without setting format edited text is "glued" with line number.

**Comment by coldnew** [comment]
@krzysztof-magosa Can you give me more information? How do you set the linum-format ?

**Comment by krzysztof-magosa** [comment]
Hi @coldnew.
I just use
```
(setq linum-format " %4d ")
```

**Comment by krzysztof-magosa** [comment]
https://asciinema.org/a/a4cudqza7rdmt9ruhyk1rfvhd

**Comment by krzysztof-magosa** [comment]
Nevermind. Looked into source, and set it via 'linum-relative-format'.
Works great. Cheers.

```
(setq linum-relative-format "%3s ")
```
