### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by sondr3** [coldnew/linum-relative#32]
I haven't been to customize the colors set by this plugin, and am a bit of a Emacs newbie so I'm not sure where to begin to look. I managed to change everything else I wanted and tried to change the colors, but couldn't get it to work.

This is how it looks: ![screen shot 2016-02-28 at 03 33 04](https://cloud.githubusercontent.com/assets/2280539/13377075/067dca66-ddcc-11e5-86fb-aa3db8ceded8.png). I don't want that black background on the current line, but not sure where to change it.

**Comment by coldnew** [comment]
You can customize the current face by **M-x customize-group** and select **linum-relative** group , you'll see customize setting like below:
<img width="1392" alt="screen shot 2016-02-28 at 6 22 59 pm" src="https://cloud.githubusercontent.com/assets/39703/13378664/55b8dbe4-de48-11e5-9eda-4fdfe9117b8e.png">

Or just add following code to your .emacs :)

```emacs-lisp
(custom-set-faces '(linum-relative-current-face
                    ((t :inherit linum :foreground "red" :background "white" :weight bold))))
```

**Comment by sondr3** [comment]
Fantastic, thanks a lot!
