### ISSUE TITLE
Show current line number instead of marker (->)

### ISSUE THREAD

**Issue by ZzAntares** [coldnew/linum-relative#33]
Hello, I was wondering what setting should be applied in order to display the real line number of the current line instead of the marker `->` which for me isn't very useful.

Thanks

**Comment by ZzAntares** [comment]
Nevermind, [I just have found it](https://github.com/coldnew/linum-relative/blob/master/linum-relative.el#L77):

```
(defcustom linum-relative-current-symbol "0"
  "The symbol you want to show on the current line, by default it is 0.
   You can use any string like \"->\". If this variable is empty string,
linum-releative will show the real line number at current line."
  :type 'string
  :group 'linum-relative)
```

**Comment by aksiksi** [comment]
This does not work on display-line-numbers-mode. Any suggestions to get this working?
