### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by arunisaac** [coldnew/linum-relative#39]
I'm packaging linum-relative for GNU Guix. It would be nice to have a new release. There hasn't been one in a long time despite many changes.

**Comment by coldnew** [comment]
@arunisaac sure, I'll do it tonight.

**Comment by coldnew** [comment]
Done :)

**Comment by arunisaac** [comment]
linum-relative has been packaged for GNU Guix. :-)

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26292
